# This document is generated by the Mongo query profiler.
# They live in the 'system.profile' collection of each database.
class MongoProfile
    include Mongoid::Document
    store_in collection: 'system.profile'

    field :ts, type: Time
    field :op, type: String
    field :command, type: Hash
    field :query, type: Hash
    field :millis, type: Integer
    field :nscanned, type: Integer
    field :execStats, type: Hash

    def duration
        millis.milliseconds
    end

    class << self
        def with_model(model, &block)
            with(database: model.collection.database.name, &block)
        end
    end
end
